{% set name = "pyiron_experimental" %}
{% set version = "0.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_experimental-{{ version }}.tar.gz
  sha256: d333970e5db6aadf976ce5abcb44c8d57a6d9fef1b2b673737ed25cfc5336167

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyiron_base >=0.6.6
    - matplotlib-base >=3.8.1
    - pystem >=0.0.26
    - hyperspy >=1.7.5
    - scanf >=1.5.2

test:
  imports:
    - pyiron_experimental
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_experimental
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Repository for experimental plugins to the pyiron IDE.'
  description: |
    Repository for experimental plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_experimental
  dev_url: https://github.com/pyiron/pyiron_experimental

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
