{% set name = "pyiron_experimental" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/pyiron-experimental/{{ name }}-{{ version }}.tar.gz
  sha256: 4a6d6c38893b73070eef22ee6d88e891b58046e509be8d04c0264136f3b7f389

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - hyperspy >=1.6.4
    - pyiron_base >=0.3.5
    - pystem >=0.0.26
    - python >3.5
    - scanf >=1.5.2
    - temmeta >=0.0.6

test:
  imports:
    - pyiron_experimental
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_experimental
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Repository for experimental plugins to the pyiron IDE.'
  description: |
    Repository for experimental plugins to the pyiron IDE.
  doc_url: https://github.com/pyiron/pyiron_experimental
  dev_url: https://github.com/pyiron/pyiron_experimental

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
